### PR TITLE
Base Docker on Build essentials for planned swarm features

### PR DESCRIPTION
**Pull request by klaas1979**
Hi Jon,

as requested. I did change the names to cyberdojofoundation and added you as maintainer.

Regards
Klaas

### CODE REVIEW

**Comment by JonJagger** [comment]
Hi Klaas,
I've installed the new Javascript-jasmine on cyber-dojo.org and pushed the docker images to the cyberdojofoundation index/hub.
I notice there is a new file called jasmine.json
Is this a file users would be expected to edit at all?

**Comment by klaas1979** [comment]
Hi Jon,

yeah you are right, the jasmine.json is a config file that is referenced from the cyber-dojo.sh script and it should normally never be edited. There was a feature to "grey out" the files, can you add the necessary configuration or tell me where i find it?

**Comment by JonJagger** [comment]
Hi Klass,
I've added jasmine.json as a lowlight filename.

The new Javascript-jasmine is on cyber-dojo.org but its name on the create page is displayed as simply language?=Javascript and test?=jasmine

When you do a cyber-dojo the info stored against your hex-id is *not* the docker image name. Or the name of a languages/ sub-folder. It's the display name. I keep version numbers out of the display names.
If the docker image that the display name maps to changes then you are automatically upgraded.
So for example, suppose you do a cyber-dojo for C#NUnit, later its docker image is upgraded, later still you fork from the original cyber-dojo, your new forked cyber-dojo will be for the *new* docker image.
The mapping takes place in Languages.rb new_name()
Does this help?

Cheers
Jon

**Comment by klaas1979** [comment]
No I got it, thank you. And thank you for your ultra fast replies and help updating the language & test version!

Regards Klaas

**Pull request merged**
