### PR TITLE
Cpp improvements on new master

### PR DESCRIPTION
**Pull request by byran**
Now uses the new languages location and moves a few more unit test frameworks include CppUTest as per James request to g++ 5.3 and C++ 14.

What started as tidying up the clang 3.6.1 image and derived unittest frameworks to make them smaller changed into something a little bigger.

I didn't modify any of the update scripts as I've not quite worked out how they work yet.

Compiler updates:
* Added gcc 5.3, including:
  - Boost 1.60
  - Microsoft GSL
  - Fake Function Framework (fff.h)
* Updated clang to 3.8.0 (C++ & C)
* Removed g++ 4.8.4 and 4.9

Unittest framework updates:
* Modified makefiles based of gpp-5.3 to build as c++ 14
* Added clang_googlemock
* Added clang_igloo
* clang_assert now based on clang-3.8.0
* clang_googletest now based on clang-3.8.0
* gpp_assert now based on gpp-5.3
* gpp_boosttest now based on gpp-5.3
* gpp_catch now based on gpp-5.3
* gpp_cpputest now based on gpp-5.3
* gpp_googletest now based on gpp-5.3
* gpp_googlemock now based on gpp-5.3
* gpp_igloo now based gpp-5.3

I've created the images so they are based on each other to try and save space. The image tree is:
* gpp-5.3 *(language)*
  * gpp_assert
  * gpp_boosttest
  * gpp_catch
  * gpp_cpputest
  * gpp_googletest
  * gpp_googlemock
  * gpp_igloo
  * clangpp-3.8.0 *(language)*
    * clangpp_assert
    * clangpp_googlemock
    * clangpp_googletest
    * clangpp_igloo
    * clang-3.8.0 *(language)*
      * clang_assert

### CODE REVIEW

**Comment by JonJagger** [comment]
Thanks Byran,
will pull this when I get home. Away trying to catch a salmon again :-)

**Comment by byran** [comment]
Good luck with the fishing.

**Comment by JonJagger** [comment]
Hi Byran,
I'm looking at the pull request now.
The file app/languages/C++ (clang++)/_docker_context/Dockerfile
The first line is
FROM       cyberdojofoundation/gpp-5.3
is that what you meant? 

I thought gpp-5.3 was g++ based and this is in the clang++ folder.

**Comment by byran** [comment]
Hi Jon,

Yes that is on purpose, it's for two reasons:

   1. It's based on gpp-5.3 so it inherits boost, gsl and fff.h and a C++14
   version of libstdc++. The clang image isn't using libc++, I may look at
   this in the future. The old clangpp image did the same thing but in a
   slightly more hidden manner as it was based on build-essential which would
   have included what ever version of libstdc++ came with g++ 4.8.
   2. It keeps the total size of docker images down. If it wasn't based on
   gpp-5.3 the clangpp image would have it's own version of libstdc++ and
   boost which are quite large.

I've also based the clang-3.8.0 (C) image on the clangpp-3.8.0 (C++) image
as they are identical in terms of what goes into the image.

If you don't like it I'm happy to change it.

Byran

**Comment by JonJagger** [comment]
Ah that makes sense. 
Happy to go with that. 
Cheers

**Pull request merged**
